version: '3'

vars:
  VERSION:  v1.0.0

tasks:
  default:
    cmds:
      - task: fetch

  fetch:
    desc: "fetch component dependencies"
    cmds:
      - mkdir -p ./vendor/{{.VERSION}} && rm -rf ./vendor/{{.VERSION}}/*
      - curl https://gist.github.com/alankrantas/63fab63fe14cec872b542eed31092fc6/raw/1b22a4d6f45b4de06bf23503aca85c4b4cd1d965/echo.yaml -o ./vendor/{{.VERSION}}/echo.yaml