# https://taskfile.dev/usage
version: '3'

tasks:
  default:
    cmds:
      - task: build

  setup:
    desc: Install required tools
    cmds:
      - echo "todo"
      # install kr8p from homebrew tap
      - brew install ice-bergtech/tap/kr8p

  build:
    desc: Generate cluster configurations with kr8
    aliases:
      - b
    cmds:
      - kr8p generate

  build-debug:
    desc: Generate cluster configurations with kr8
    aliases:
      - bd
    cmds:
      - kr8p generate --debug
