# https://taskfile.dev/usage
version: '3'

vars:
  CHART_VER:  v2.17.0
  CHART_NAME: sealed-secrets
  CHART_REPO: 'https://bitnami-labs.github.io/sealed-secrets'

tasks:
  default:
    cmds:
      - task: fetch-chart

  fetch-chart:
    desc: "fetch component dependencies"
    cmds:
      - mkdir -p ./vendor/{{.CHART_NAME}}-{{.CHART_VER}} && rm -rf ./vendor/{{.CHART_NAME}}-{{.CHART_VER}}/*
      - mkdir -p ./tmp && rm -rf ./tmp/*
      # add the helm repo and fetch it locally into vendor directory
      - helm fetch --repo {{.CHART_REPO}} --untar --untardir ./tmp --version "{{.CHART_VER}}" "{{.CHART_NAME}}"
      - mv ./tmp/{{.CHART_NAME}}/* ./vendor/{{.CHART_NAME}}-{{.CHART_VER}}/ && rm -rf ./tmp