version: '3'

vars:
  CHART_VER:  v1.14.0
  CHART_NAME: external-dns
  CHART_REPO: 'https://kubernetes-sigs.github.io/external-dns/'

tasks:
  default:
    cmds:
      - task: fetch

  fetch:
    desc: "fetch component dependencies"
    cmds:
      - mkdir -p ./vendor/{{.CHART_NAME}}-{{.CHART_VER}} && rm -rf ./vendor/{{.CHART_NAME}}-{{.CHART_VER}}/*
      - mkdir -p ./tmp && rm -rf ./tmp/*
      # add the helm repo and fetch it locally into vendor directory
      - helm fetch --repo {{.CHART_REPO}} --untar --untardir ./tmp --version "{{.CHART_VER}}" "{{.CHART_NAME}}"
      - mv ./tmp/{{.CHART_NAME}}/* ./vendor/{{.CHART_NAME}}-{{.CHART_VER}}/ && rm -rf ./tmp